apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.env.name }}"
  name: "{{ .Values.env.service }}"
  namespace: "{{ .Values.env.namespace.compute }}"
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6000
  selector:
    app: {{ .Values.env.name }}
  sessionAffinity: None
  type: ClusterIP